services:
  wallet_balance:
    class: "cli/WalletBalance"
    tags:
      - { name: "solfege.console.command" }

  wallet_from_mnemonic:
    class: "cli/WalletFromMnemonic"
    tags:
      - { name: "solfege.console.command" }

  mnemonic_random:
    class: "cli/MnemonicRandom"
    tags:
      - { name: "solfege.console.command" }

  mnemonic_validate:
    class: "cli/MnemonicValidate"
    tags:
      - { name: "solfege.console.command" }

  mnemonic_seed:
    class: "cli/MnemonicSeed"
    tags:
      - { name: "solfege.console.command" }

  exchange_binance_get_balances:
    class: "cli/exchange/binance/GetBalances"
    arguments:
      - "%exchanges%"
    tags:
      - { name: "solfege.console.command" }

  exchange_binance_get_open_orders:
    class: "cli/exchange/binance/GetOpenOrders"
    arguments:
      - "%exchanges%"
    tags:
      - { name: "solfege.console.command" }

  aggregator_cryptocompare_get_asset_price:
    class: "cli/aggregator/cryptocompare/GetAssetPrice"
    arguments:
      - "%aggregators.cryptocompare.apiKey%"
    tags:
      - { name: "solfege.console.command" }

