services:
  wallet_balance:
    class: "cli/wallet/GetBalance.command"
    tags:
      - { name: "solfege.console.command" }

  wallet_from_mnemonic:
    class: "cli/wallet/GetInfoFromMnemonic.command"
    tags:
      - { name: "solfege.console.command" }

  mnemonic_random:
    class: "cli/wallet/MnemonicRandom.command"
    tags:
      - { name: "solfege.console.command" }

  mnemonic_validate:
    class: "cli/wallet/MnemonicValidate.command"
    tags:
      - { name: "solfege.console.command" }

  mnemonic_seed:
    class: "cli/wallet/MnemonicSeed.command"
    tags:
      - { name: "solfege.console.command" }

  exchange_binance_get_balances:
    class: "cli/exchange/binance/GetBalances.command"
    arguments:
      - "%exchanges%"
    tags:
      - { name: "solfege.console.command" }

  exchange_binance_get_open_orders:
    class: "cli/exchange/binance/GetOpenOrders.command"
    arguments:
      - "%exchanges%"
    tags:
      - { name: "solfege.console.command" }

  exchange_kucoin_get_balances:
    class: "cli/exchange/kucoin/GetBalances.command"
    arguments:
      - "%exchanges%"
    tags:
      - { name: "solfege.console.command" }

  portfolio_get_balances:
    class: "cli/portfolio/GetBalances.command"
    arguments:
      - "%exchanges%"
    tags:
      - { name: "solfege.console.command" }

  aggregator_cryptocompare_get_asset_price:
    class: "cli/aggregator/cryptocompare/GetAssetPrice.command"
    arguments:
      - "%aggregators.cryptocompare.apiKey%"
    tags:
      - { name: "solfege.console.command" }

